apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-app-pvc
spec:
  volumeName: volume-app-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
