apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-deployment
  type: ClusterIP 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - name: auth
        image: linsted/k8s-networking:auth-api