apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks-deployment
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-deployment
  template:
    metadata:
      labels:
        app: tasks-deployment
    spec:
      containers:
      - name: tasks-deployment
        image: linsted/k8s-networking:tasks
        imagePullPolicy: Always
        env:
          - name: AUTH_ADDRESS
            value: "auth-service.default"
          - name: TASKS_FOLDER
            value: "tasks"
