apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  selector:
    app: k8s-deployment
  type: LoadBalancer 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployment
  template:
    metadata:
      labels:
        app: k8s-deployment
    spec:
      containers:
      - name: k8s-deployment
        image: linsted/k8s-networking:latest
        imagePullPolicy: Always
        env:
          - name: AUTH_ADDRESS
        #   value: localhost #hardcoded for now
            value: "auth-service.default"
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        # ports:
        # - containerPort: <Port>
