apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-demo-deployment-app
  template:
   metadata:
     labels:
       app: k8s-demo-deployment-app
   spec:
    containers:
     - name: second-node-app
       image: linsted/kub-demo-app